appsync commands

diff --git a/goolfc b/goolfc
--- a/goolfc
+++ b/goolfc
@@ -37,6 +37,20 @@ EB_GOOLFC="goolfc-${GOOLFC_VER}.eb"
 DATE=$(date +%Y-%m-%d)
 EB_HEADER="# $DATE generated by goolfc script (Ruoshi Sun)"
 
+# temporary file for appsync commands
+APPSYNC_FILE="$(mktemp)"
+APPSYNC=(
+    "compiler gcc/$GCC_VER openblas/$OPENBLAS_VER"
+    "compiler gcc/$GCC_VER cuda/$CUDA_VER "
+    "toolchains gcccuda/$GCCCUDA_VER"
+    "compiler gcc-cuda/${GCCCUDA_VER/_/-} openmpi/$OPENMPI_VER"
+    "toolchains gompic/$GOMPIC_VER"
+    "mpi gcc-cuda/${GCCCUDA_VER/_/-} openmpi/$OPENMPI_VER scalapack/$SCALAPACK_VER"
+    "mpi gcc-cuda/${GCCCUDA_VER/_/-} openmpi/$OPENMPI_VER fftw/$FFTW_VER"
+    "toolchains goolfc/$GOOLFC_VER"
+)
+
+# menu and prompt
 MESSAGE=(
     "openblas/$OPENBLAS_VER with gcc/$GCC_VER"
     "cuda/$CUDA_VER with gcc/$GCC_VER"
@@ -48,23 +62,33 @@ MESSAGE=(
     "goolfc/$GOOLFC_VER toolchain"
 )
 
-# confirmation
-echo "goolfc automatic install (Ruoshi Sun)"
+echo "   <G>cc"
+echo "   <O>penmpi"
+echo "   <O>penblas"
+echo "sca<L>apack"
+echo "   <F>ftw"
+echo "   <C>uda      automatic installation (Ruoshi Sun)"
+echo
+
 for i in "${!MESSAGE[@]}"; do 
     echo "$i. ${MESSAGE[$i]}"
 done
+echo
 
 read -p "Select initial step [0-7]: " step
-if [[ $step -lt 0 || $step -gt 7 ]]; then
-    echo "Exiting"
+if ! [[ "$step" =~ ^[0-7]$ ]]; then
+    echo "Invalid option."
     exit 1
 fi
+
+#----------------------------------------- 
+# begin installation
 
 module purge
 module load easybuild
 
 # 0. openblas with gcc
-if [ $step -le 0 ]; then
+if [ $step -eq 0 ]; then
     cat > $EB_OPENBLAS <<EOF
 $EB_HEADER
 easyblock = 'ConfigureMake'
@@ -127,7 +151,7 @@ sources = ['%(name)s_%(version)s_418.67_linux.run']
 moduleclass = 'system'
 EOF
 
-    eb $EB_CUDA
+    eb -f $EB_CUDA
 fi
 
 # 2. gcccuda toolchain
@@ -157,7 +181,7 @@ dependencies = [
 moduleclass = 'toolchain'
 EOF
 
-    eb $EB_GCCCUDA
+    eb -f $EB_GCCCUDA
 fi
 
 # 3. openmpi with gcccuda
@@ -202,7 +226,7 @@ modextravars = {
 moduleclass = 'mpi'
 EOF
 
-    eb $EB_OPENMPI
+    eb -f $EB_OPENMPI
 fi
 
 # 4. gompic toolchain
@@ -236,7 +260,7 @@ dependencies = [
 
 moduleclass = 'toolchain'
 EOF
-    eb $EB_GOMPIC
+    eb -f $EB_GOMPIC
 fi
 
 # 5. scalapack with gompic
@@ -274,7 +298,7 @@ parallel = 1
 moduleclass = 'numlib'
 EOF
 
-    eb $EB_SCALAPACK
+    eb -f $EB_SCALAPACK
 fi
 
 # 6. fftw with gompic
@@ -309,7 +333,7 @@ configopts = [
 moduleclass = 'numlib'
 EOF
 
-    eb $EB_FFTW
+    eb -f $EB_FFTW
 fi
 
 # 7. goolfc
@@ -320,9 +344,9 @@ easyblock = 'Toolchain'
 
 name = 'goolfc'
 
-gccver  = '6.5.0'
-mpiver = '3.1.4'
-cudaver = '10.1.168'
+gccver  = '$GCC_VER'
+mpiver = '$OPENMPI_VER'
+cudaver = '$CUDA_VER'
 
 version = '%s_%s_%s' % (gccver,mpiver,cudaver)
 
@@ -340,14 +364,37 @@ gompic_tc  = ('gompic',  '%s_%s' % (gccver, mpiver))
 dependencies = [
     comp,
     ('openmpi',   mpiver,  '', gcccuda_tc),
-    ('openblas',  '0.3.7', '', comp),
-    ('scalapack', '2.1.0', '', gompic_tc),
-    ('fftw',      '3.3.8', '', gompic_tc),
+    ('openblas',  '$OPENBLAS_VER', '', comp),
+    ('scalapack', '$SCALAPACK_VER', '', gompic_tc),
+    ('fftw',      '$FFTW_VER', '', gompic_tc),
     ('cuda',      cudaver, '', comp),
 ]
 
 moduleclass = 'toolchain'
 EOF
 
-    eb $EB_GOOLFC
+    eb -f $EB_GOOLFC
 fi
+
+#----------------------------------------- 
+# write appsync commands
+
+YYYYMM_SRC=`ls -l /apps | awk -F'/' '{print $NF}'`
+YYYYMM_DEST=${YYYYMM_SRC/_build/}
+
+cat > $APPSYNC_FILE <<EOF
+for i in $YYYYMM_DEST; do
+EOF
+
+for i in "${!APPSYNC[@]}"; do 
+    if [ $i -ge $step ]; then
+        echo "    appsync $YYYYMM_DEST \$i ${APPSYNC[$i]}" >>$APPSYNC_FILE
+    fi
+done
+
+echo "done" >>$APPSYNC_FILE
+chmod +x $APPSYNC_FILE
+
+echo
+echo "appsync commands in $APPSYNC_FILE"
+cat $APPSYNC_FILE
